### ISSUE TITLE
Check for HM_ENV_TYPE environment variable

### ISSUE THREAD

**Issue by goldenapples** [humanmade/PHPBasicAuth#2]
Rather than requiring users to define an `HM_DEV` constant which doesn't exist by default, I'm wondering if it'd make sense to use the existing `HM_ENV_TYPE` constant and checking for 'development' or 'staging' values.

https://www.altis-dxp.com/resources/docs/core/#environment

**Comment by joemcgill** [comment]
I noticed this too, and think that it would be cool if this plugin was completely environment agnostic. We could build an Altis specific wrapper for it that checked for config settings before enabling/disabling.

Perhaps another option is to have a filter that short circuited the `enabled` value so an outside environment could add code that changed the value based on external factors like environment values, datestamps, etc.
