### ISSUE TITLE
hmauth_filter_dev_env ignored when credentials are already set

### ISSUE THREAD

**Issue by stuartshields** [humanmade/PHPBasicAuth#21]
@jazzsequence So when working on a short-circuit for a client project, I noticed that on the following line:
```
( $hm_dev || $altis_dev || $creds_defined || $other_dev )
```
in https://github.com/humanmade/PHPBasicAuth/blob/407d1b0b04e5b1b01a36eaed00a00fd63f4c1802/inc/namespace.php#L63

`$other_dev` is ignored because `$creds_defined` is checked before `$other_dev`. While I understand the reasoning behind this, I think we need to do the following:
```
( $hm_dev || $altis_dev || $other_dev  || $creds_defined )
```

This is so we can still set the credentials via composer for the other environment, but not activate it until the filter `$other_dev = apply_filters( 'hmauth_filter_dev_env', false );` is set. 

I'll create a PR based on this idea and await your feedback.

**Comment by jazzsequence** [comment]
Fixed in #22
